import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { SinService } from './selectedSins/sin-service';

@Component({
  selector: 'app-home',
  templateUrl: './confession.component.html',
  styleUrls: ['./confession.component.css']
})
export class ConfessionComponent {
  sins = ["Involvement in occult practices, e.g., witchcraft, ouija boards, seances, palm reading, tarot cards, hypnotism, divination, astrology, black magic, sorcery, etc.",
  "Involvement in or adherence to New Age or Eastern philosophies, atheism or agnosticism",
  "Apostasy (leaving the Church)",
  "Adherence to a schismatic group",
  "Putting faith in superstition, e.g., horoscopes, good luck charms, etc.",
  "Joining the Masons or other secret society",
  "Receiving Holy Communion in the state of mortal sin",
  "Receiving the Sacraments of Confirmation or Matrimony while in the state of mortal sin",
  "Willful participation in illicit (non-emergency) “General Absolution” services",
  "Being married by a Justice of the Peace or by a minister of another denomination (without dispensation)",
  "Involvement in false or pagan worship",
  "Willfully denying the Faith of the Catholic Church",
  "Despair of God’s grace or mercy",
  "Presumption (committing a mortal sin with the idea that you can just go to confession)",
  "Hatred of God",
  "Simony (buying or selling spiritual things)",
  "Failure to receive Holy Communion at least once per year ( if possible, during the Easter Season)",
  "Desecration of the Holy Eucharist",
  "Using God’s name intentionally as a curse",
  "Seriously wishing evil upon another",
  "Serious slander or insult of a sacred person or object",
  "Making an oath in a secret society",
  "Telling a lie or withholding a serious sin in confession",
  "Blasphemy (words of hatred, reproach or defiance toward God; speaking ill of God)",
  "Perjury (lying under oath)",
  "Swearing false oaths",
  "Missing Mass on Sunday or a Holy Day of Obligation without a serious reason",
  "Doing unnecessary work on Sunday for a long period of time, i.e., more than several hours",
  "Intentional failure to fast or abstain on appointed days",
  "Requiring employees to work on Sunday in nonessential occupations",
  "Serious failure to care for aged parents",
  "Serious neglect of the duties of one’s state in life",
  "Serious disrespect for or disobedience to parents, superiors or authorities",
  "Wishing death or evil on parents",
  "Abuse or serious neglect of children",
  "Failure to baptize children in a reasonable time (within a few months) after birth",
  "Serious neglect of the religious education or upbringing of children",
  "Failure to carry out the last will of deceased parents",
  "Murder, homicide or manslaughter",
  "Procurement of an abortion",
  "Promoting, counseling or paying for an abortion",
  "Knowingly voting for someone who is proabortion",
  "Willfully injuring or trying to hurt another person",
  "Willfully leading another into serious sin",
  "Driving dangerously or recklessly",
  "Driving under the influence of drugs or alcohol",
  "Willfully harboring hatred for another",
  "Taking or selling illegal drugs",
  "Willful drunkenness",
  "Self mutilation",
  "Excessive tattoos",
  "Excessive body piercing",
  "Piercing of the nipples or sexual organs",
  "Sterilization",
  "Promotion of or involvement in euthanasia",
  "Serious entertainment of suicidal thoughts",
  "Attempting or intending suicide",
  "Willful failure to bury the body or ashes of the dead",
  "Willful engagement in unjust lawsuits",
  "Bigotry (hatred for persons of other races)",
  "Intentionally placing temptation before the weak",
  "Adultery",
  "Fornication (intercourse prior to marriage)",
  "Masturbation or other impure acts with self",
  "Homosexual acts",
  "Using a contraceptive",
  "Dressing or acting in a manner intended to cause arousal in another (spouses excepted)",
  "Kissing or touching another passionately for the purpose of arousal (spouses excepted)",
  "Allowing another to kiss or touch you in a sexual manner (spouses excepted)",
  "Intentionally causing a sexual climax outside of intercourse",
  "Onanism, i.e. intentional withdrawal and nonvaginal ejaculation",
  "Flagrant immodesty in dress",
  "Bestiality (sexual acts with animals)",
  "Oral sex (permitted as foreplay in marriage)",
  "Anal sex or other degrading sex practices",
  "Prostitution",
  "Rape",
  "In-vitro fertilization or artificial insemination",
  "Surrogate motherhood",
  "“Selective reduction” of babies in the womb",
  "Types of fertility testing that involve immoral acts",
  "Involvement in or support of human cloning",
  "Willful divorce or desertion",
  "Incest",
  "Polygamy or polyandry (many wives/husbands)",
  "Cohabitation prior to marriage",
  "Destroying the innocence of another by seducing or introducing them to immorality",
  "Lust in the heart (“if I could I would”)",
  "“Swinging” or wife swapping",
  "Transvestitism or cross dressing",
  "Stealing a large amount of money or a valuable item",
  "Willfully destroying or defacing another’s property",
  "Stealing something consecrated to God or from a holy place",
  "Buying, selling, receiving or concealing items known to be stolen",
  "Willful failure to make restitution",
  "Excessive gambling",
  "Defrauding workers of their wages",
  "Serious failure to fulfill work requirements",
  "Padding expense or per diem accounts",
  "Taking advantage of the poor, simple, inexperienced or less fortunate",
  "Denying help to the poor, needy or destitute when able to help them easily",
  "Defrauding creditors",
  "Bribery or taking bribes",
  "Blackmail",
  "Fraud or embezzlement",
  "Price fixing",
  "Tax evasion",
  "Forgery",
  "Excessive waste or expense",
  "Violating copyrights",
  "Pirating computer software",
  "Slavery",
  "Serious cruelty to animals",
  "False witness (not under oath) or perjury (under oath)",
  "Telling large or premeditated lies",
  "Serious gossip, detraction (revealing the faults of another without serious reason), or calumny (harming the reputation of another by falsities)",
  "Violation of a confidence without good reason",
  "Being an accomplice to another’s grave sin",
  "Viewing pornography in books, magazines, movies, the internet, etc.",
  "Reading sexually explicit materials",
  "Dwelling on impure thoughts or fantasies for the purpose of arousal",
  "Willfully lusting after another",
  "Serious and willful greed or avarice",
  "Intention to steal or destroy the goods of another",

//VENIAL SINS
  "Failure to pray on a daily basis",
  "Not trying to love God with my whole mind, heart, soul and strength",
  "Trying to control things rather than seek God’s will",
  "Entertaining doubts against the Faith",
  "Failing to seek out or learn the teachings of the Church",
  "Indifference or ingratitude to God",
  "Lukewarmness in the relationship with God",
  "Not trying to grow spiritually; being content with mediocrity",
  "Acedia (spiritual sloth)",
  "Putting other things or people before God, e.g., TV, radio, sports, hobbies, etc.",
  "Attachment to human respect or affection, i.e., caring more about what others think than what God thinks in order to fit in or be liked",
  "Not trusting God",
  "Failure to fulfill the duties of one’s state in life",
  "Playing Dungeons and Dragons or similar games",
  "Tempting God",
  "Being angry at God",
  "Embarrassment of being Catholic",
  "Failure to defend the Church when ridiculed",
  "Failure to support the work of the Church monetarily and/or with time and ability",
  "Not taking part in the work of evangelization",
  "Being willfully distracted at Mass or in prayer",
  "Putting off confession needlessly",
  "Failing to accept or offer up suffering",
  "Refusing or denying the mercy of God",
  "Not trying to practice recollection or the frequent remembrance of God’s presence",
  "Failure to pray when tempted",
  "Failure to examine one’s conscience daily",
  "Giving into depression, self-pity or self-deprecating thoughts",

  "Using the Lord’s name lightly, in surprise or in anger (habitual, not thinking)",
    "Cursing thoughtlessly",
    "Using the names of Mary, a Saint, the Pope or other sacred persons irreverently",
    "Using vulgar or inappropriate language",
    "Telling bad jokes about sacred persons or objects",
    "Speaking badly of the Church",
    "Inappropriate or irreverent use of Scripture",

    "Doing unnecessary work on Sunday",
    "Failing to keep Sunday as a day for family and recreation",
    "Failing to spend extra time on Sunday in prayer and study of the Faith",
    "Allowing sports or other schedules to dictate the Sunday schedule",
    "Being irreverent in church",
    "Not paying attention or participating at Mass",
    "Coming late to Mass or leaving early without a serious reason",
    "Desecrating the day by sinful amusements, bad company, inappropriate entertainment, etc.",

    "Fighting with siblings",
    "Treating those under one’s authority disrespectfully",
    "Failure to respect the dignity of children",
    "Speaking badly about parents",
    "Speaking badly about children",
    "Speaking badly about one’s spouse",
    "Neglecting duties toward spouse or children",
    "Failing to give good example to one’s family",
    "Not trying to cultivate peace in the family",
    "Taking one’s spouse for granted",
    "Making fun of or failing to help the elderly or handicapped",
    "Not praying for those entrusted to your care",
    "Failing to pray for those in authority over you, e.g., parents, teachers, employers, government officials, etc.",
    "Failure to teach children adequately about God and the spiritual life",
    "Lack of gratitude toward parents",
    "Nagging spouse or children",
    "Treating adult children like minors",
    "Meddling in the affairs of married children",
    "Too lax with rules, boundaries and discipline",
    "Too strict with rules, boundaries and discipline",
    "Breaking just civil laws without serious reason",
    "Being ashamed of or embarrassed about parents",
    "Disobedience to parents or authorities",
    "Failure to give proper respect to parents or those in authority",

    "Pride, arrogance",
    "Vanity",
    "Stubbornness without good reason",
    "Rudeness",
    "Failure to apologize",
    "Fighting or arguing over slight matters",
    "Anger",
    "Using obscene or vulgar gestures",
    "Prejudice",
    "Harboring a grudge",
    "Seeking revenge or retaliation",
    "Wishing evil upon another",
    "Impatience",
    "Selfishness",
    "Listening to bad music",
    "Excessive watching of television",
    "Excessive playing of computer games",
    "Excessive use of the internet",
    "Watching TV or movies that promote sex or violence",
    "Playing computer games that promote sex or violence",
    "Refusing to forgive another",
    "Intemperance (overeating or drinking too much)",
    "Driving carelessly",
    "Failing to care for one’s health",
    "Smoking or chewing tobacco",
    "Abusing medications",
    "Sloth (laziness)",
    "Procrastination",
    "Lack of punctuality",
    "Failure to respect the dignity of self or others",
    "Giving scandal to another",
    "Treating another unjustly",
    "Failure to take medications if such are necessary",
    "Doing things willfully to anger others",
    "Violating friendships",
    "Failure to pray for deceased parents or relatives",
    "Using the “silent treatment” on others",
    "Failure to pray for sinners",

    "Lack of custody of the eyes (looking inappropriately at others)",
    "Allowing the heart to stray from one’s spouse",
    "Dressing somewhat immodestly",
    "Acting or carrying oneself immodestly",
    "Treating others as objects",
    "Failure to respect persons of the opposite sex",
    "Seeking wrongful attention from another",
    "Selfishness in marital intimacy",
    "Failure to be open to life without serious reason",
    "Keeping bad company",

    "Attachments to persons or things",
    "Theft of small or inexpensive items",
    "Willful Failure to return borrowed items",
    "Wasting time",
    "Failure to pay debts promptly",
    "Failing to practice charity or to help the poor",
    "Squandering money on needless things or pursuits",
    "Not keeping a promise",

    "Lying",
    "Gossiping",
    "Spreading rumors or tale bearing",
    "Talking behind another’s back",
    "Being negative, critical or uncharitable in thought regarding others",
    "Making rash judgments",
    "Being unjustly suspicious",
    "Failure to seek to restore the good name of another whom you have injured through speech",
    "Cheating in games, school work, etc.",
    "Speaking unkindly to or about others",
    "Exaggerating the truth",
    "Bragging or boasting",
    "Flattery",
    "Complaining, whining or attention seeking",

    "Telling or listening to impure or vulgar jokes or stories",
    "Brief entertainment of impure thoughts or fantasies",
    "Not trying to control the imagination",
    "Curiosity or playing with temptation",
    "Seeking out or looking at persons or pictures which are immodest",

    "Envy (sadness or anger at the good fortune of another)",
    "Jealousy (desire for the goods of another)",
    "Greed",
    "Materialism",
    "Not trusting that God will provide for all material and spiritual needs",
    "Attachment to riches or material goods"
]; // Replace with your sins
  selectedSins: string[] = [];
  sinChecked: boolean[] = [];

  constructor(private router: Router, private sinService: SinService) { 
    this.sinChecked = new Array(this.sins.length).fill(false);
  }

  navigateHome() {
    this.router.navigate(['']);
  }

  onSinClick(index: number) {
    this.sinChecked[index] = !this.sinChecked[index];
    if (this.sinChecked[index]) {
      this.selectedSins.push(this.sins[index]);
    } else {
      this.selectedSins = this.selectedSins.filter(sin => sin !== this.sins[index]);
    }
  }

  onSinChange(index: number, event: any) {
    if (!event.target.checked) {
      this.sinChecked[index] = false;
      this.selectedSins = this.selectedSins.filter(sin => sin !== this.sins[index]);
    }
  }
  

  onSubmit() {
    this.sinService.setSelectedSins(this.selectedSins); // Set the selected sins
    this.router.navigate(['/selected-sins']); // Navigate to the new component
  }
}
